apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-3rtb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-3rtb
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-3rtb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-3rtb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-3rtb
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jdcd-tenant/rhtap-demo-app/hacbs-test-project-3rtb@sha256:86234822fa3d554c95a3ed93275e6b8881a438cee8bf6357d383ab9c510ccc33
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
