apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-3rtb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jdcd-tenant/rhtap-demo-app/hacbs-test-project-3rtb@sha256:497a5c7787d886b63f7597d72a315bef2e96cffc676ab471ec7256883ed7b1d3
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
