apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-3rtb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jdcd-tenant/rhtap-demo-app/hacbs-test-project-3rtb@sha256:86234822fa3d554c95a3ed93275e6b8881a438cee8bf6357d383ab9c510ccc33
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
